In [23]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
import pandas_profiling
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import seaborn as sns
sns.set(style="ticks", color_codes=True)
from scipy import stats


from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_squared_log_error
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import Imputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Lasso, Ridge

In [2]:
import eda
import regression as reg
%reload_ext autoreload
%autoreload 2

In [3]:
pd.set_option("display.max_columns", 999)
pd.set_option("display.max_rows", 60)
pd.set_option('max_colwidth', 20)

In [4]:
#Get the latest listings.csv.gz from http://insideairbnb.com/get-the-data.html
#Then convert it to pandas dataframe

df_london = pd.read_csv("/Users/valmadrid/DataScienceBootcamp/Projects/Mod4/London Airbnb Listing Detailed.csv")
#df_london = pd.read_csv("http://data.insideairbnb.com/united-kingdom/england/london/2019-09-14/data/listings.csv.gz")

In [5]:
df_london.head()

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,number_of_reviews_ltm,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,11551.0,https://www.airb...,2.019091e+13,2019-09-15,Arty and Bright ...,Unlike most rent...,Amenities Beddin...,Unlike most rent...,family,Not even 10 minu...,No Smoking (very...,Tons of buses (2...,Guest will have ...,No interaction w...,No Smoking (very...,NaN,NaN,https://a0.musca...,NaN,43039,https://www.airb...,Adriano,2009-10-03,"London, England,...","Hello, I'm a fri...",within an hour,100%,NaN,t,https://a0.musca...,https://a0.musca...,Brixton,3.0,3.0,"['email', 'phone...",t,t,"London, United K...",Brixton,Lambeth,NaN,London,NaN,SW9 8DG,London,"London, United K...",GB,United Kingdom,51.46225,-0.11732,t,Apartment,Entire home/apt,4.0,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",I...",NaN,$88.00,$645.00,"$2,350.00",$400.00,$30.00,2.0,$20.00,2.0,180.0,2,2.0,180.0,180,2.0,180.0,4 days ago,t,19.0,42.0,72.0,344.0,2019-09-15,184.0,1.0,2010-03-21,2019-07-10,92.0,9.0,9.0,10.0,10.0,9.0,9.0,f,NaN,NaN,t,f,strict_14_with_g...,f,t,2.0,2.0,0.0,0.0,1.59
1,13913.0,https://www.airb...,2.019091e+13,2019-09-15,Holiday London D...,My bright double...,"Hello Everyone, ...",My bright double...,business,Finsbury Park is...,For art lovers I...,The flat only a ...,Guest will have ...,I like to have l...,I'm an artist an...,NaN,NaN,https://a0.musca...,NaN,54730,https://www.airb...,Alina,2009-11-16,"London, England,...",I am a Multi-Med...,within an hour,100%,NaN,f,https://a0.musca...,https://a0.musca...,LB of Islington,4.0,4.0,"['email', 'phone...",t,f,"Islington, Great...",LB of Islington,Islington,NaN,Islington,Greater London,N4 3,London,"Islington, Unite...",GB,United Kingdom,51.56802,-0.11121,t,Apartment,Private room,2.0,1.0,1.0,0.0,Real Bed,"{TV,""Cable TV"",W...",538.0,$65.00,$333.00,"$1,176.00",$100.00,$15.00,1.0,$15.00,1.0,29.0,1,1.0,29.0,29,1.0,29.0,5 months ago,t,18.0,48.0,78.0,353.0,2019-09-15,16.0,2.0,2010-08-18,2019-06-10,96.0,9.0,10.0,9.0,10.0,9.0,9.0,f,NaN,NaN,f,f,moderate,f,f,3.0,1.0,2.0,0.0,0.14
2,15400.0,https://www.airb...,2.019091e+13,2019-09-15,Bright Chelsea ...,Lots of windows ...,Bright Chelsea A...,Lots of windows ...,romantic,It is Chelsea.,The building nex...,The underground ...,There are two wa...,If I am in the c...,NO SMOKING PLEAS...,NaN,NaN,https://a0.musca...,NaN,60302,https://www.airb...,Philippa,2009-12-05,"Kensington, Engl...","English, grandmo...",within a few hours,100%,NaN,t,https://a0.musca...,https://a0.musca...,Chelsea,1.0,1.0,"['email', 'phone...",t,t,"London, United K...",Chelsea,Kensington and C...,NaN,London,NaN,SW3,London,"London, United K...",GB,United Kingdom,51.48796,-0.16898,t,Apartment,Entire home/apt,2.0,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",I...",NaN,$100.00,$600.00,"$2,250.00",$150.00,$50.00,2.0,$0.00,30.0,50.0,30,30.0,50.0,50,30.0,50.0,4 days ago,t,8.0,8.0,8.0,114.0,2019-09-15,87.0,6.0,2009-12-21,2019-08-27,96.0,10.0,10.0,10.0,10.0,10.0,9.0,f,NaN,NaN,t,f,strict_14_with_g...,t,t,1.0,1.0,0.0,0.0,0.73
3,17402.0,https://www.airb...,2.019091e+13,2019-09-15,Superb 3-Bed/2 B...,You'll have a wo...,This is a wonder...,You'll have a wo...,none,"Location, locati...",This property ha...,You can walk to ...,Full use of whol...,Always available...,The apartment be...,NaN,NaN,https://a0.musca...,NaN,67564,https://www.airb...,Liz,2010-01-04,"London, England,...",We are Liz and J...,within an hour,98%,NaN,t,https://a0.musca...,https://a0.musca...,Fitzrovia,18.0,18.0,"['email', 'phone...",t,t,"London, Fitzrovi...",City of Westminster,Westminster,NaN,London,Fitzrovia,W1T4BP,London,"London, United K...",GB,United Kingdom,51.52098,-0.14002,t,Apartment,Entire home/apt,6.0,2.0,3.0,4.0,Real Bed,"{TV,Wifi,Kitchen...",NaN,$300.00,"$1,378.00",NaN,$350.00,$65.00,4.0,$10.00,3.0,365.0,2,3.0,365.0,365,3.0,365.0,5 days ago,t,12.0,36.0,54.0,265.0,2019-09-15,41.0,5.0,2011-03-21,2019-06-19,94.0,10.0,9.0,9.0,9.0,10.0,9.0,f,NaN,NaN,t,f,strict_14_with_g...,f,f,15.0,15.0,0.0,0.0,0.40
4,24328.0,https://www.airb...,2.019091e+13,2019-09-15,Battersea bedroo...,"Artist house, br...",- End of terrace...,"Artist house, br...",family,- Battersea is a...,- Please have a ...,- 5 mins walk to...,- there is a com...,We rent out our ...,A house manual w...,NaN,NaN,https://a0.musca...,NaN,41759,https://www.airb...,Joe,2009-09-28,"London, England,...",I've been using ...,within a day,80%,NaN,f,https://a0.musca...,https://a0.musca...,Battersea,0.0,0.0,"['email', 'phone...",t,t,"London, United K...",LB of Wandsworth,Wandsworth,NaN,London,NaN,SW11 5GX,London,"London, United K...",GB,United Kingdom,51.47298,-0.16376,t,Townhouse,Entire home/apt,2.0,1.5,1.0,1.0,Real Bed,"{TV,""Cable TV"",I...",1001.0,$175.00,"$1,050.00","$3,500.00",$250.00,$70.00,2.0,$0.00,30.0,1125.0,30,30.0,1125.0,1125,30.0,1125.0,6 months ago,t,11.0,41.0,71.0,346.0,2019-09-15,93.0,1.0,2010-11-15,2019-06-08,98.0,10.0,10.0,10.0,10.0,9.0,9.0,f,NaN,NaN,f,f,moderate,t,t,1.0,1.0,0.0,0.0,0.86

In [ ]:
#Run a profiling report for initial EDA

london_report = df_london.profile_report(title="London Airbnb Listing Detailed Profiling Report")
london_report.to_file(output_file="londondetailed.html")

In [6]:
columns_for_deletion = ["listing_url", "scrape_id", "name", "summary", "space", "description", "neighborhood_overview", "notes", "transit", "access", "interaction", "house_rules", 
           "thumbnail_url", "medium_url", "picture_url", "xl_picture_url", "host_id", "host_url", "host_name", "host_location", "host_about", "host_response_time", 
           "host_response_rate", "host_acceptance_rate", "host_thumbnail_url", "host_picture_url", "host_neighbourhood", "host_listings_count", 
           "host_total_listings_count", "street", "neighbourhood_group_cleansed", "city", "state", "zipcode", "market", "smart_location", "country_code", "country", 
           "square_feet", "minimum_minimum_nights", "maximum_minimum_nights", "minimum_maximum_nights", "maximum_maximum_nights", "minimum_nights_avg_ntm", 
           "maximum_nights_avg_ntm", "calendar_updated", "has_availability", "calendar_last_scraped", "license", "jurisdiction_names", "is_business_travel_ready"]

df_delete = df_london[columns_for_deletion]
df_delete.head()

,listing_url,scrape_id,name,summary,space,description,neighborhood_overview,notes,transit,access,interaction,house_rules,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,street,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,square_feet,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,calendar_updated,has_availability,calendar_last_scraped,license,jurisdiction_names,is_business_travel_ready
0,https://www.airb...,2.019091e+13,Arty and Bright ...,Unlike most rent...,Amenities Beddin...,Unlike most rent...,Not even 10 minu...,No Smoking (very...,Tons of buses (2...,Guest will have ...,No interaction w...,No Smoking (very...,NaN,NaN,https://a0.musca...,NaN,43039,https://www.airb...,Adriano,"London, England,...","Hello, I'm a fri...",within an hour,100%,NaN,https://a0.musca...,https://a0.musca...,Brixton,3.0,3.0,"London, United K...",NaN,London,NaN,SW9 8DG,London,"London, United K...",GB,United Kingdom,NaN,2,2.0,180.0,180,2.0,180.0,4 days ago,t,2019-09-15,NaN,NaN,f
1,https://www.airb...,2.019091e+13,Holiday London D...,My bright double...,"Hello Everyone, ...",My bright double...,Finsbury Park is...,For art lovers I...,The flat only a ...,Guest will have ...,I like to have l...,I'm an artist an...,NaN,NaN,https://a0.musca...,NaN,54730,https://www.airb...,Alina,"London, England,...",I am a Multi-Med...,within an hour,100%,NaN,https://a0.musca...,https://a0.musca...,LB of Islington,4.0,4.0,"Islington, Great...",NaN,Islington,Greater London,N4 3,London,"Islington, Unite...",GB,United Kingdom,538.0,1,1.0,29.0,29,1.0,29.0,5 months ago,t,2019-09-15,NaN,NaN,f
2,https://www.airb...,2.019091e+13,Bright Chelsea ...,Lots of windows ...,Bright Chelsea A...,Lots of windows ...,It is Chelsea.,The building nex...,The underground ...,There are two wa...,If I am in the c...,NO SMOKING PLEAS...,NaN,NaN,https://a0.musca...,NaN,60302,https://www.airb...,Philippa,"Kensington, Engl...","English, grandmo...",within a few hours,100%,NaN,https://a0.musca...,https://a0.musca...,Chelsea,1.0,1.0,"London, United K...",NaN,London,NaN,SW3,London,"London, United K...",GB,United Kingdom,NaN,30,30.0,50.0,50,30.0,50.0,4 days ago,t,2019-09-15,NaN,NaN,f
3,https://www.airb...,2.019091e+13,Superb 3-Bed/2 B...,You'll have a wo...,This is a wonder...,You'll have a wo...,"Location, locati...",This property ha...,You can walk to ...,Full use of whol...,Always available...,The apartment be...,NaN,NaN,https://a0.musca...,NaN,67564,https://www.airb...,Liz,"London, England,...",We are Liz and J...,within an hour,98%,NaN,https://a0.musca...,https://a0.musca...,Fitzrovia,18.0,18.0,"London, Fitzrovi...",NaN,London,Fitzrovia,W1T4BP,London,"London, United K...",GB,United Kingdom,NaN,2,3.0,365.0,365,3.0,365.0,5 days ago,t,2019-09-15,NaN,NaN,f
4,https://www.airb...,2.019091e+13,Battersea bedroo...,"Artist house, br...",- End of terrace...,"Artist house, br...",- Battersea is a...,- Please have a ...,- 5 mins walk to...,- there is a com...,We rent out our ...,A house manual w...,NaN,NaN,https://a0.musca...,NaN,41759,https://www.airb...,Joe,"London, England,...",I've been using ...,within a day,80%,NaN,https://a0.musca...,https://a0.musca...,Battersea,0.0,0.0,"London, United K...",NaN,London,NaN,SW11 5GX,London,"London, United K...",GB,United Kingdom,1001.0,30,30.0,1125.0,1125,30.0,1125.0,6 months ago,t,2019-09-15,NaN,NaN,f

In [ ]:
delete = df_delete.profile_report(title="Columns For Deletion - Profiling Report")
delete.to_file(output_file="delete.html")

In [7]:
#Delete highly correlated or similar columns and those with only null values based on the Profiling Report 
#Delete columns which will not be used modeling

df_londonairbnb = df_london.drop(columns_for_deletion, axis = 1)
df_londonairbnb.dropna(subset = ["id"], axis = 0, inplace = True) #all disctint listings except for one null value
df_londonairbnb.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85273 entries, 0 to 85273
Data columns (total 55 columns):
id                                              85273 non-null float64
last_scraped                                    85273 non-null object
experiences_offered                             85273 non-null object
host_since                                      85257 non-null object
host_is_superhost                               85256 non-null object
host_verifications                              85272 non-null object
host_has_profile_pic                            85256 non-null object
host_identity_verified                          85256 non-null object
neighbourhood                                   85272 non-null object
neighbourhood_cleansed                          85272 non-null object
latitude                                        85272 non-null float64
longitude                                       85272 non-null float64
is_location_exact                               85272 non-null object
property_type                                   85272 non-null object
room_type                                       85272 non-null object
accommodates                                    85272 non-null float64
bathrooms                                       85145 non-null float64
bedrooms                                        85230 non-null float64
beds                                            85119 non-null float64
bed_type                                        85272 non-null object
amenities                                       85272 non-null object
price                                           85272 non-null object
weekly_price                                    7191 non-null object
monthly_price                                   5129 non-null object
security_deposit                                55620 non-null object
cleaning_fee                                    63743 non-null object
guests_included                                 85272 non-null float64
extra_people                                    85272 non-null object
minimum_nights                                  85272 non-null float64
maximum_nights                                  85272 non-null float64
availability_30                                 85272 non-null float64
availability_60                                 85272 non-null float64
availability_90                                 85272 non-null float64
availability_365                                85272 non-null float64
number_of_reviews                               85272 non-null float64
number_of_reviews_ltm                           85272 non-null float64
first_review                                    64269 non-null object
last_review                                     64269 non-null object
review_scores_rating                            62590 non-null float64
review_scores_accuracy                          62539 non-null float64
review_scores_cleanliness                       62552 non-null float64
review_scores_checkin                           62491 non-null float64
review_scores_communication                     62546 non-null float64
review_scores_location                          62492 non-null float64
review_scores_value                             62491 non-null float64
requires_license                                85272 non-null object
instant_bookable                                85272 non-null object
cancellation_policy                             85272 non-null object
require_guest_profile_picture                   85272 non-null object
require_guest_phone_verification                85272 non-null object
calculated_host_listings_count                  85272 non-null float64
calculated_host_listings_count_entire_homes     85272 non-null float64
calculated_host_listings_count_private_rooms    85272 non-null float64
calculated_host_listings_count_shared_rooms     85272 non-null float64
reviews_per_month                               64269 non-null float64
dtypes: float64(28), object(27)
memory usage: 36.4+ MB

In [9]:
#Run another profiling report after deleting columns

# london_report2 = df_londonairbnb.profile_report(title="London Airbnb Listing Detailed Profiling Report (2)")
# london_report2.to_file(output_file="londondetailed2.html")

In [ ]:
# london_report2

In [ ]:
#sns.pairplot(df_londonairbnb, y_vars = df_londonairbnb.price, x_vars = df_londonairbnb.drop(["price"], axis = 1));

In [ ]:
#sns.pairplot(df_londonairbnb, y_vars = df_londonairbnb.price, x_vars = df_londonairbnb.bathrooms);

In [10]:
#Check the zero and null values of continuous features

df_londonairbnb.select_dtypes("float64").info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85273 entries, 0 to 85273
Data columns (total 28 columns):
id                                              85273 non-null float64
latitude                                        85272 non-null float64
longitude                                       85272 non-null float64
accommodates                                    85272 non-null float64
bathrooms                                       85145 non-null float64
bedrooms                                        85230 non-null float64
beds                                            85119 non-null float64
guests_included                                 85272 non-null float64
minimum_nights                                  85272 non-null float64
maximum_nights                                  85272 non-null float64
availability_30                                 85272 non-null float64
availability_60                                 85272 non-null float64
availability_90                                 85272 non-null float64
availability_365                                85272 non-null float64
number_of_reviews                               85272 non-null float64
number_of_reviews_ltm                           85272 non-null float64
review_scores_rating                            62590 non-null float64
review_scores_accuracy                          62539 non-null float64
review_scores_cleanliness                       62552 non-null float64
review_scores_checkin                           62491 non-null float64
review_scores_communication                     62546 non-null float64
review_scores_location                          62492 non-null float64
review_scores_value                             62491 non-null float64
calculated_host_listings_count                  85272 non-null float64
calculated_host_listings_count_entire_homes     85272 non-null float64
calculated_host_listings_count_private_rooms    85272 non-null float64
calculated_host_listings_count_shared_rooms     85272 non-null float64
reviews_per_month                               64269 non-null float64
dtypes: float64(28)
memory usage: 18.9 MB

In [11]:
#Delete rows where column has only one nan value

nan_to_delete = ["latitude", "longitude","accommodates", "guests_included", "minimum_nights", "maximum_nights", "availability_365", "calculated_host_listings_count"]
df_londonairbnb.dropna(subset = nan_to_delete, axis = 0, inplace = True)

In [ ]:
#Check which proxy to be used for zero and null values

for col in list(df_londonairbnb.select_dtypes("float64").columns):
    eda.check_zero_nan(df_londonairbnb[col], replace = "mode")

In [12]:
#bathrooms proxy 1 (mode) for null and zeroes
df_londonairbnb.bathrooms = eda.replace_zero_nan(df_londonairbnb.bathrooms, 1)

#bedrooms proxy 0 for null and zeroes, assume studio type for bedrooms = 0
df_londonairbnb.bedrooms = eda.replace_zero_nan(df_londonairbnb.bedrooms, 0)

#bed proxy 1 (mode) for null and zeroes
df_londonairbnb.beds = eda.replace_zero_nan(df_londonairbnb.beds, 1)

#review scores and count proxy 0 for null
df_londonairbnb.review_scores_rating = eda.replace_zero_nan(df_londonairbnb.review_scores_rating, replace = 0)
df_londonairbnb.review_scores_accuracy = eda.replace_zero_nan(df_londonairbnb.review_scores_accuracy, replace = 0)
df_londonairbnb.review_scores_cleanliness = eda.replace_zero_nan(df_londonairbnb.review_scores_cleanliness, replace = 0)
df_londonairbnb.review_scores_communication = eda.replace_zero_nan(df_londonairbnb.review_scores_communication, replace = 0)
df_londonairbnb.review_scores_checkin = eda.replace_zero_nan(df_londonairbnb.review_scores_checkin, replace = 0)
df_londonairbnb.review_scores_location = eda.replace_zero_nan(df_londonairbnb.review_scores_location, replace = 0)
df_londonairbnb.review_scores_value = eda.replace_zero_nan(df_londonairbnb.review_scores_value, replace = 0)
df_londonairbnb.reviews_per_month = eda.replace_zero_nan(df_londonairbnb.reviews_per_month, replace = 0)

#reviews_per_month proxy 0 for null values
df_londonairbnb.reviews_per_month = eda.replace_zero_nan(df_londonairbnb.reviews_per_month, 0)

#Check if all float columns have been dealt with
df_londonairbnb.select_dtypes("float64").info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85272 entries, 0 to 85273
Data columns (total 28 columns):
id                                              85272 non-null float64
latitude                                        85272 non-null float64
longitude                                       85272 non-null float64
accommodates                                    85272 non-null float64
bathrooms                                       85272 non-null float64
bedrooms                                        85272 non-null float64
beds                                            85272 non-null float64
guests_included                                 85272 non-null float64
minimum_nights                                  85272 non-null float64
maximum_nights                                  85272 non-null float64
availability_30                                 85272 non-null float64
availability_60                                 85272 non-null float64
availability_90                                 85272 non-null float64
availability_365                                85272 non-null float64
number_of_reviews                               85272 non-null float64
number_of_reviews_ltm                           85272 non-null float64
review_scores_rating                            85272 non-null float64
review_scores_accuracy                          85272 non-null float64
review_scores_cleanliness                       85272 non-null float64
review_scores_checkin                           85272 non-null float64
review_scores_communication                     85272 non-null float64
review_scores_location                          85272 non-null float64
review_scores_value                             85272 non-null float64
calculated_host_listings_count                  85272 non-null float64
calculated_host_listings_count_entire_homes     85272 non-null float64
calculated_host_listings_count_private_rooms    85272 non-null float64
calculated_host_listings_count_shared_rooms     85272 non-null float64
reviews_per_month                               85272 non-null float64
dtypes: float64(28)
memory usage: 18.9 MB

In [13]:
#Next, check null and zero values of categorical columns

df_londonairbnb.select_dtypes("object").info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85272 entries, 0 to 85273
Data columns (total 27 columns):
last_scraped                        85272 non-null object
experiences_offered                 85272 non-null object
host_since                          85256 non-null object
host_is_superhost                   85256 non-null object
host_verifications                  85272 non-null object
host_has_profile_pic                85256 non-null object
host_identity_verified              85256 non-null object
neighbourhood                       85272 non-null object
neighbourhood_cleansed              85272 non-null object
is_location_exact                   85272 non-null object
property_type                       85272 non-null object
room_type                           85272 non-null object
bed_type                            85272 non-null object
amenities                           85272 non-null object
price                               85272 non-null object
weekly_price                        7191 non-null object
monthly_price                       5129 non-null object
security_deposit                    55620 non-null object
cleaning_fee                        63743 non-null object
extra_people                        85272 non-null object
first_review                        64269 non-null object
last_review                         64269 non-null object
requires_license                    85272 non-null object
instant_bookable                    85272 non-null object
cancellation_policy                 85272 non-null object
require_guest_profile_picture       85272 non-null object
require_guest_phone_verification    85272 non-null object
dtypes: object(27)
memory usage: 18.2+ MB

In [14]:
#Delete rows where column has <50 nan values

nan_to_delete = ["host_since", "host_is_superhost", "host_has_profile_pic", "host_identity_verified"]
df_londonairbnb.dropna(subset = nan_to_delete, axis = 0, inplace = True)
df_londonairbnb.select_dtypes("object").info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85256 entries, 0 to 85273
Data columns (total 27 columns):
last_scraped                        85256 non-null object
experiences_offered                 85256 non-null object
host_since                          85256 non-null object
host_is_superhost                   85256 non-null object
host_verifications                  85256 non-null object
host_has_profile_pic                85256 non-null object
host_identity_verified              85256 non-null object
neighbourhood                       85256 non-null object
neighbourhood_cleansed              85256 non-null object
is_location_exact                   85256 non-null object
property_type                       85256 non-null object
room_type                           85256 non-null object
bed_type                            85256 non-null object
amenities                           85256 non-null object
price                               85256 non-null object
weekly_price                        7186 non-null object
monthly_price                       5125 non-null object
security_deposit                    55616 non-null object
cleaning_fee                        63736 non-null object
extra_people                        85256 non-null object
first_review                        64262 non-null object
last_review                         64262 non-null object
requires_license                    85256 non-null object
instant_bookable                    85256 non-null object
cancellation_policy                 85256 non-null object
require_guest_profile_picture       85256 non-null object
require_guest_phone_verification    85256 non-null object
dtypes: object(27)
memory usage: 18.2+ MB

In [15]:
#Check which proxy to be used for zero and null values

for col in list(df_londonairbnb.select_dtypes("object").columns):
    eda.check_zero_nan_object(df_londonairbnb[col])

column name =  weekly_price
null values =  78070
zeroes =  0

$300.00    295
$500.00    276
$250.00    254
$350.00    251
$600.00    248
$200.00    229
$400.00    212
$700.00    182
$450.00    181
$550.00    147
Name: weekly_price, dtype: int64

column name =  monthly_price
null values =  80131
zeroes =  0

$2,000.00    166
$1,000.00    157
$1,200.00    154
$800.00      138
$1,500.00    137
$900.00      127
$2,500.00    123
$3,000.00    116
$1,400.00    105
$1,800.00    104
Name: monthly_price, dtype: int64

column name =  security_deposit
null values =  29640
zeroes =  0

$0.00      19619
$100.00     6014
$200.00     4994
$250.00     3644
$300.00     3322
$500.00     3283
$150.00     2904
$85.00      1958
$495.00     1324
$350.00     1017
Name: security_deposit, dtype: int64

column name =  cleaning_fee
null values =  21520
zeroes =  0

$0.00     5938
$20.00    5240
$30.00    5103
$10.00    4547
$50.00    3880
$15.00    3689
$40.00    3677
$25.00    3271
$60.00    2506
$35.00    1961
Name: cleaning_fee, dtype: int64

column name =  first_review
null values =  20994
zeroes =  0

2019-07-07    234
2019-01-01    222
2019-07-14    199
2019-06-30    196
2019-06-02    185
2019-08-11    176
2019-01-02    170
2019-04-28    162
2019-08-04    162
2018-01-01    161
Name: first_review, dtype: int64

column name =  last_review
null values =  20994
zeroes =  0

2019-08-26    1312
2019-09-01    1258
2019-09-08    1147
2019-08-25    1137
2019-08-27    1086
2019-08-31    1070
2019-08-30     969
2019-08-18     954
2019-09-12     849
2019-08-28     780
Name: last_review, dtype: int64

In [16]:
#weekly_price proxy 0 for null values
df_londonairbnb.weekly_price = eda.replace_zero_nan(df_londonairbnb.weekly_price, "$0.00")

#monthly_price proxy 0 for null values
df_londonairbnb.monthly_price = eda.replace_zero_nan(df_londonairbnb.monthly_price, "$0.00")

#security_deposit proxy 0 for null values
df_londonairbnb.security_deposit = eda.replace_zero_nan(df_londonairbnb.security_deposit, "$0.00")

#cleaning_fee proxy 0 for null values
df_londonairbnb.cleaning_fee = eda.replace_zero_nan(df_londonairbnb.cleaning_fee, "$0.00")

df_londonairbnb.select_dtypes("object").info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85256 entries, 0 to 85273
Data columns (total 27 columns):
last_scraped                        85256 non-null object
experiences_offered                 85256 non-null object
host_since                          85256 non-null object
host_is_superhost                   85256 non-null object
host_verifications                  85256 non-null object
host_has_profile_pic                85256 non-null object
host_identity_verified              85256 non-null object
neighbourhood                       85256 non-null object
neighbourhood_cleansed              85256 non-null object
is_location_exact                   85256 non-null object
property_type                       85256 non-null object
room_type                           85256 non-null object
bed_type                            85256 non-null object
amenities                           85256 non-null object
price                               85256 non-null object
weekly_price                        85256 non-null object
monthly_price                       85256 non-null object
security_deposit                    85256 non-null object
cleaning_fee                        85256 non-null object
extra_people                        85256 non-null object
first_review                        64262 non-null object
last_review                         64262 non-null object
requires_license                    85256 non-null object
instant_bookable                    85256 non-null object
cancellation_policy                 85256 non-null object
require_guest_profile_picture       85256 non-null object
require_guest_phone_verification    85256 non-null object
dtypes: object(27)
memory usage: 18.2+ MB

In [17]:
#Update categorical columns with values 't' and 'f', then change dtype to 'int64'

t_or_f = ["host_is_superhost", "host_has_profile_pic", "host_identity_verified", "is_location_exact", "require_guest_phone_verification",
         "require_guest_profile_picture", "instant_bookable", "requires_license"]

eda.binary_col(df_londonairbnb, t_or_f)
df_londonairbnb[t_or_f].head()

,host_is_superhost,host_has_profile_pic,host_identity_verified,is_location_exact,require_guest_phone_verification,require_guest_profile_picture,instant_bookable,requires_license
0,1,1,1,1,1,0,1,0
1,0,1,0,1,0,0,0,0
2,1,1,1,1,1,1,1,0
3,1,1,1,1,0,0,1,0
4,0,1,1,1,1,1,0,0

In [18]:
#Convert money columns to 'float64'

money_columns = ["price", "weekly_price", "monthly_price", "security_deposit", "cleaning_fee", "extra_people"]
eda.update_money_columns(df_londonairbnb, money_columns)
df_londonairbnb.select_dtypes("object").info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85256 entries, 0 to 85273
Data columns (total 13 columns):
last_scraped              85256 non-null object
experiences_offered       85256 non-null object
host_since                85256 non-null object
host_verifications        85256 non-null object
neighbourhood             85256 non-null object
neighbourhood_cleansed    85256 non-null object
property_type             85256 non-null object
room_type                 85256 non-null object
bed_type                  85256 non-null object
amenities                 85256 non-null object
first_review              64262 non-null object
last_review               64262 non-null object
cancellation_policy       85256 non-null object
dtypes: object(13)
memory usage: 9.1+ MB

In [19]:
#Convert 'host_since' and 'last_review' to number of days

df_londonairbnb['host_days'] = pd.to_datetime(df_londonairbnb['last_scraped']) - pd.to_datetime(df_londonairbnb['host_since'])
df_londonairbnb["days_from_last_review"] = pd.to_datetime(df_londonairbnb['last_scraped']) - pd.to_datetime(df_london['last_review'])
df_londonairbnb['host_days'] = df_londonairbnb['host_days']/ np.timedelta64(1, 'D')
df_londonairbnb["days_from_last_review"] = df_londonairbnb["days_from_last_review"] / np.timedelta64(1, 'D')
df_londonairbnb["days_from_last_review"].fillna(value = 0, inplace = True)

In [20]:
df_londonairbnb.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 85256 entries, 0 to 85273
Data columns (total 57 columns):
id                                              85256 non-null float64
last_scraped                                    85256 non-null object
experiences_offered                             85256 non-null object
host_since                                      85256 non-null object
host_is_superhost                               85256 non-null int64
host_verifications                              85256 non-null object
host_has_profile_pic                            85256 non-null int64
host_identity_verified                          85256 non-null int64
neighbourhood                                   85256 non-null object
neighbourhood_cleansed                          85256 non-null object
latitude                                        85256 non-null float64
longitude                                       85256 non-null float64
is_location_exact                               85256 non-null int64
property_type                                   85256 non-null object
room_type                                       85256 non-null object
accommodates                                    85256 non-null float64
bathrooms                                       85256 non-null float64
bedrooms                                        85256 non-null float64
beds                                            85256 non-null float64
bed_type                                        85256 non-null object
amenities                                       85256 non-null object
price                                           85256 non-null float64
weekly_price                                    85256 non-null float64
monthly_price                                   85256 non-null float64
security_deposit                                85256 non-null float64
cleaning_fee                                    85256 non-null float64
guests_included                                 85256 non-null float64
extra_people                                    85256 non-null float64
minimum_nights                                  85256 non-null float64
maximum_nights                                  85256 non-null float64
availability_30                                 85256 non-null float64
availability_60                                 85256 non-null float64
availability_90                                 85256 non-null float64
availability_365                                85256 non-null float64
number_of_reviews                               85256 non-null float64
number_of_reviews_ltm                           85256 non-null float64
first_review                                    64262 non-null object
last_review                                     64262 non-null object
review_scores_rating                            85256 non-null float64
review_scores_accuracy                          85256 non-null float64
review_scores_cleanliness                       85256 non-null float64
review_scores_checkin                           85256 non-null float64
review_scores_communication                     85256 non-null float64
review_scores_location                          85256 non-null float64
review_scores_value                             85256 non-null float64
requires_license                                85256 non-null int64
instant_bookable                                85256 non-null int64
cancellation_policy                             85256 non-null object
require_guest_profile_picture                   85256 non-null int64
require_guest_phone_verification                85256 non-null int64
calculated_host_listings_count                  85256 non-null float64
calculated_host_listings_count_entire_homes     85256 non-null float64
calculated_host_listings_count_private_rooms    85256 non-null float64
calculated_host_listings_count_shared_rooms     85256 non-null float64
reviews_per_month                               85256 non-null float64
host_days                                       85256 non-null float64
days_from_last_review                           85256 non-null float64
dtypes: float64(36), int64(8), object(13)
memory usage: 40.2+ MB

In [ ]:
#Transform amenities to categorical columns

amenities = list(df_londonairbnb.amenities)
amenities = " ".join(amenities_list).replace('{', '').replace('}', ',').replace('"', '')
amenities = [x.strip() for x in amenities_list_string.split(',')]
amenities = list(set(amenities_set))
amenities

In [21]:
df_londonairbnb.to_csv("londonairbnb_cleaned.csv", index = False)

In [ ]:
#Outliers: remove those outside 3*std
x = df_londonairbnb[(np.abs(stats.zscore(df_londonairbnb)) < 3).all(axis = 1)]

In [ ]:
x

In [ ]:
#Model no. 1

X_columns_exlude = ['id', 'last_scraped', 'host_since', 'amenities', 'host_verifications', 'neighbourhood', 'latitude', 'longitude', 'weekly_price',
                   'monthly_price', 'availability_30', 'availability_60', 'availability_90', 'first_review','last_review', 'price',
                    'calculated_host_listings_count', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin',
                    'review_scores_communication', 'review_scores_location','review_scores_value']

X = df_londonairbnb.drop(columns = X_columns_exlude, axis=1)
y = df_londonairbnb[["price"]]

model1 = pd.concat([y,X], axis = 1)
model1.head()

In [ ]:
#Run a profiling report again

model1_report = model1.profile_report(title="MODEL1 London Airbnb Listing Detailed Profiling Report")
model1_report.to_file(output_file="model1.html")

In [ ]:
model1_report

In [ ]:
X_train, X_test, y_train, y_test = reg.preprocess(X, y)

In [ ]:
#First Linear Regression Model

train_R2, test_R2, train_mse, test_mse, coefs, intercept = reg.run_linear(X_train, X_test, y_train, y_test)

print('Training r^2:', train_R2)
print('Testing r^2:', test_R2)
print('Training MSE:', train_mse)
print('Testing MSE:', test_mse)

In [ ]:
#First LASSO model

lasso_table = reg.run_lasso(X_train, X_test, y_train, y_test)
lasso_table.head()

In [ ]:
#First Ridge model

ridge_table = reg.run_ridge(X_train, X_test, y_train, y_test)
ridge_table.head()

In [ ]:
#Model no. 2

X_columns_exlude = ['id', 'last_scraped', 'host_since', 'amenities', 'host_verifications', 'neighbourhood', 'latitude', 'longitude', 'weekly_price',
                   'monthly_price', 'availability_30', 'availability_60', 'availability_90', 'first_review','last_review', 'price',
                    'calculated_host_listings_count', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin',
                    'review_scores_communication', 'review_scores_location','review_scores_value', 'bedrooms', 'beds', 'number_of_reviews',
                    'reviews_per_month']

X2 = df_londonairbnb.drop(columns = X_columns_exlude, axis=1)
y2 = df_londonairbnb[["price"]]

model2 = pd.concat([y,X], axis = 1)
model2.head()

In [ ]:
#model1.corr().unstack().sort_values(ascending = False).drop_duplicates().tail(20)